import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.sass"
import {getLocale, getMessages} from "next-intl/server"
import {NextIntlClientProvider} from "next-intl"

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
    title: "Rudenko Maksym",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const locale = await getLocale()

    const messages = await getMessages()

    return (
        <html lang={locale} data-theme="dark">
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
